name: CI-NextPhase

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D ts-jest @types/jest @testing-library/jest-dom

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: |
          npm test -- --ci --runInBand --detectOpenHandles